name: "Code Quality Composite Action JS"
description: "A composite action to run linting and static code analysis for a JavaScript project."
inputs:
  skip-tests:
    description: "skip tests"
    required: false
    default: false
  working-directory:
    required: false
    default: ''
outputs:
  lint-report:
    description: "The JSON lint report output from ESLint."
defaults:
    run:
      # Set the default shell to bash for all steps in this action
      # This is useful if you want to use bash-specific features in your scripts
      shell: bash
      working-directory: ${{ inputs.working-directory }}
runs:
  using: "composite"

  steps:
    - name: Install Dependencies
      run: npm install

    - name: Run Linting
      id: run_lint
      run: |
        npx eslint . --format json > lint-report.json

    - name: Run Unit Tests (Optional)
      if: ${{ inputs.skip-tests == 'false' }}
      run: npm test

    - name: Set Lint Report Output
      run: echo "lint-report=$(cat lint-report.json)" >> $GITHUB_OUTPUT
