name: Build Java Application
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test with Maven
        run: mvn clean install
        working-directory: java-app

      - name: Package Application
        run: mvn package -D skipTests=true
        working-directory: java-app

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-package
          path: java-app/target/*.jar