# This workflow will build a Java project with Maven
##
## More details on https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Build a Java Application with checkstyle

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-with-checkstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        # Set the working directory to the java-app directory
        # works only for the shell.
        working-directory: java-app
    outputs:
      # Propagate the output from the code quality action to be used in other jobs
      checkstyle-artifact-url: ${{ steps.checkstyle.outputs.checkstyle-artifact-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run Code Quality Action
        id: checkstyle
        uses: ./.github/actions/code-quality-java
        with:
          working-directory: java-app
  log-output:
    runs-on: ubuntu-latest
    needs: build-with-checkstyle
    steps:
      - name: Print the output
        # Print the output from the previous job
        run: |
          echo "The checkstyle report is available at ${{ needs.build-with-checkstyle.outputs.checkstyle-artifact-url }}"
