name: CI Workflow

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo "🛠️ Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/bugfix/')
    steps:
      - name: Run Tests
        run: echo "✅ Testing on ${{ github.ref }}"

  bugfix-check:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/bugfix/')
    steps:
      - name: Run Bugfix Validation
        run: echo "🕵️ Bugfix validation for ${{ github.ref }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Deploy
        run: echo "🚀 Deploying tag ${{ github.ref }}"
