name: Debug the Mess

on: workflow_dispatch

env:
  MY_VAR: "Workflow Level Value"

jobs:
  debug-vars:
    runs-on: ubuntu-latest
    env:
      MY_VAR: "Job Level Value"

    steps:
      - name: Define a Step-Level Variable
        run: echo "MY_VAR=$MY_VAR"
        env:
          MY_VAR: "Step Level Value"

      - name: Override with GITHUB_ENV
        run: |
          echo "MY_VAR=Overridden via GITHUB_ENV" >> $GITHUB_ENV

      - name: Print the final value
        run: echo "Final MY_VAR value is $MY_VAR"
