# This workflow will print a variable at each level of the workflow, job, and step.
name: Precedence Puzzle

on: workflow_dispatch

env:
  GREETING: "Hello from workflow"

jobs:
  check-precedence:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello from job"

    steps:
      - name: Step 1 - Local override
        run: |
          echo "GREETING in step 1: $GREETING"
        env:
          GREETING: "Hello from step"

      - name: Step 2 - Use GitHub context
        run: |
          echo "GREETING in step 2: ${{ env.GREETING }}"

      - name: Step 3 - Set with GITHUB_ENV
        run: echo "GREETING=Hello from GITHUB_ENV" >> $GITHUB_ENV

      - name: Step 4 - Evaluate in shell
        run: |
          echo "GREETING in step 4 (shell): $GREETING"

      - name: Step 5 - Evaluate in GitHub context
        run: |
          echo "GREETING in step 5 (context): ${{ env.GREETING }}"
