name: Variable Precedence Puzzle

on: [push]

jobs:
  puzzle:
    runs-on: ubuntu-latest

    env:
      GLOBAL_VAR: "I am global"
      SHARED_VAR: "Global shared"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set step-level variable
        env:
          STEP_VAR: "I am step-level"
          SHARED_VAR: "Step-level shared"
        run: echo "Step-Level Variable $STEP_VAR"

      - name: Set environment variable
        run: echo "ENV_VAR=I am environment" >> $GITHUB_ENV

      - name: Override global variable
        run: echo "GLOBAL_VAR=I am overridden" >> $GITHUB_ENV

      - name: Print variables
        run: |
          echo "Global Variable: $GLOBAL_VAR"
          echo "Environment Variable: $ENV_VAR"
          echo "Shared Variable: $SHARED_VAR"

      - name: Use secret
        run: echo "Secret Value ${{ secrets.MY_SECRET }}"
        env:
          MY_SECRET: "Not the real secret"
