name: Debug the Mess

on: workflow_dispatch

env:
  MY_VAR: "Workflow Level Value"

jobs:
  debug-vars:
    runs-on: ubuntu-latest
    env:
      MY_VAR: "Job Level Value"

    steps:
      - name: Define a Step-Level Variable
        env:
          MY_VAR: "Step Level Value"
        run: echo "MY_VAR is $MY_VAR"

      - name: Print the Variable
        run: echo "MY_VAR is $MY_VAR"

      - name: Override with GITHUB_ENV
        run: |
          echo "MY_VAR=Overridden via GITHUB_ENV" >> $GITHUB_ENV

      - name: Print the final value
        # What happens if we don't use the env keyword?
        run: echo "Final MY_VAR value is $MY_VAR"

      - name: Print the final value 2
        run: echo "Final MY_VAR value is ${{ env.MY_VAR }}"


