## You can use the GitHub API to trigger a webhook event called repository_dispatch to run this workflow.
##
##  POST /repos/{owner}/{repo}/dispatches
##  Accept: application/vnd.github+json"
##  Authorization: Bearer <YOUR-TOKEN>
##  X-GitHub-Api-Version: 2022-11-28
##
##  {
##    "event_type":"custom-event-type",
##    "client_payload":{
##      "unit":false,
##      "integration":true
##    }
##  }
##
##
## More details on https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch
## To create a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

name: External Trigger Example
on:
  repository_dispatch:
    types:
      - custom-event-type 

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ github.event.client_payload.unit}}"
