name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v3
        with:
          issue_message: |
            # Issue Message with Markdown

            Welcome, ${{ github.event.issue.user.login }},  to the project, and thank you for your contribution!
          pr_message: |
            # PR Message with Markdown

            Welcome, ${{ github.event.pull_request.user.login }},  to the project, and thank you for your contribution!